[build]
  # Directory to publish (static site)
  publish = "." # Serve files from the root directory (since build.js modifies index.html in place)
  # Command to build your site
  command = "npm run build"
  functions = "netlify/functions"

# Redirect API traffic to functions (MUST COME BEFORE SPA REDIRECT)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all other traffic to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 